global:
  resolve_timeout: 5m
receivers:
- name: ops
  webhook_configs:
  - url: http://dingtalk:8060/dingtalk/ops/send
    send_resolved: true
- name: dev
  webhook_configs:
  - url: http://dingtalk:8060/dingtalk/dev/send
    send_resolved: true
route:
  receiver: ops
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  group_by: ['cluster', 'alertname']
  routes:
  - receiver: dev
    group_wait: 10s
    match:
      team: dev
